### ISSUE TITLE
Just curious about `jsonapi-resources`

### ISSUE THREAD

**Issue by tenzan** [Simplify/rails5_json_api_demo#1]
Hello!

Thanks for the interesting tutorial.

Just curious if you tried https://github.com/cerebris/jsonapi-resources?

If yes, why did you prefer `active_model_serializers` over `jsonapi-resources` ?

Thanks.

**Comment by Simplify** [comment]
Hi @tenzan, 

Sorry about late response, I was too busy last few days. 

I get that question very often, usually via e-mail. At the time of writing that article I was not aware of JSONAPI::Resources. That is real and only reason, at that time.

3-4 months ago I had to chose right JSON:API gem for one of my clients who already had "standard" JSON API and wanted to build new API's version. Again, I chose `active_model-serializers` because at that time integration with that gem was easier if you already have some kind of JSON API and you want to support both. 

However, JSONAPI::Resources has incredibly grown last few months. If I had to chose now, decision will not be so easy. Both gems are good and have very active community. `active_model-serializers` may have a bit higher code quality and test coverage, but I really don't like their error serializer. 

I'm planning to write follow up article and maybe I will actually switch to JSONAPI::Resources :)
